import "dotenv/config";
import { getWriteDb } from "../src/db/client.js";
import { hydrateWindowsUserEnv } from "./lib/env.ts";

hydrateWindowsUserEnv();

const db = getWriteDb();
const observedAt = new Date().toISOString();

type EvidenceRow = {
  market: string;
  title: string;
  address: string;
  city: string;
  state_code: string;
  zip: string | null;
  source_url: string;
  list_price?: number | null;
  units?: number | null;
  status: "active" | "off_market";
  confidence: "medium" | "high";
  raw: Record<string, unknown>;
};

const rows: EvidenceRow[] = [
  {
    market: "indianapolis",
    title: "4500 S Keystone Ave - self-storage development land",
    address: "4500 S Keystone Ave",
    city: "Indianapolis",
    state_code: "IN",
    zip: "46227",
    source_url: "https://www.loopnet.com/Listing/4500-S-Keystone-Ave-Indianapolis-IN/40212210/",
    list_price: 600000,
    status: "active",
    confidence: "medium",
    raw: {
      evidence_type: "self_storage_development_land",
      listing_id: "40212210",
      parcel_number: "49-10-31-121-002.000-574",
      lot_acres: 8.22,
      source_summary: "LoopNet detail page says the land property is currently available and marketing text says ground is available for self-storage or multifamily use.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page plus explicit self-storage use language; classified as development land, not an operating self-storage facility.",
    },
  },
  {
    market: "indianapolis",
    title: "5815 E 42nd St - approved indoor self-storage / mini-warehouse conversion",
    address: "5815 E 42nd St",
    city: "Indianapolis",
    state_code: "IN",
    zip: "46226",
    source_url: "https://www.loopnet.com/Listing/5815-E-42nd-St-Indianapolis-IN/26041666/",
    list_price: 1200000,
    status: "active",
    confidence: "medium",
    raw: {
      evidence_type: "self_storage_conversion_opportunity",
      listing_id: "26041666",
      parcel_number: "49-07-15-110-001.000-401",
      building_sqft: 80000,
      lot_acres: 11,
      broker: "MRE Connect Brokerage",
      source_summary: "LoopNet detail page says the property is currently available and zoning/summary identify approved indoor self storage and/or mini warehousing or flex commercial.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page plus explicit approved self-storage / mini-warehouse language; classified as conversion opportunity, not an operating self-storage facility.",
    },
  },
  {
    market: "dallas",
    title: "2339 Inwood Rd - self-storage covered land play",
    address: "2339 Inwood Rd",
    city: "Dallas",
    state_code: "TX",
    zip: "75235",
    source_url: "https://www.loopnet.com/Listing/2339-Inwood-Rd-Dallas-TX/39303130/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "operating_self_storage_or_redevelopment",
      listing_id: "39303130",
      building_sqft: 31460,
      year_built_renovated: "1964/1998",
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies property subtype Self-Storage and says Weitzman is marketing the property at 2339 Inwood Road.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage.",
    },
  },
  {
    market: "dallas",
    title: "Self Storage Portfolio - Mesquite / Balch Springs",
    address: "3818 N Town East Blvd; 12504 Quail Dr",
    city: "Mesquite",
    state_code: "TX",
    zip: "75150",
    source_url: "https://www.loopnet.com/Listing/Self-Storage-Portfolio/25786169/",
    list_price: 3600000,
    units: 273,
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "self_storage_portfolio",
      listing_id: "25786169",
      activated_on: "2022-05-25",
      building_sqft: 34420,
      lot_acres: 2.51,
      portfolio_properties: 2,
      portfolio_name: "Self Storage Portfolio",
      source_summary: "LoopNet detail page says the portfolio has two storage facilities/businesses: Town East Self Storage and Balch Springs Mini Warehouses, 273 units total, status active.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with self-storage operating portfolio details.",
    },
  },
  {
    market: "dayton",
    title: "1764 Guenther Rd - in-progress self-storage development",
    address: "1764 Guenther Rd",
    city: "Dayton",
    state_code: "OH",
    zip: "45417",
    source_url: "https://www.loopnet.com/Listing/1764-Guenther-Rd-Dayton-OH/39354732/",
    list_price: 2500000,
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "self_storage_development",
      listing_id: "39354732",
      building_sqft: 36000,
      planned_buildings: 26,
      source_summary: "LoopNet detail page says the property is a partially completed self-storage development consisting of a planned 26-building facility.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit in-progress self-storage development language.",
    },
  },
  {
    market: "akron",
    title: "1025 S Broadway St - self-storage / flex building",
    address: "1025 S Broadway St",
    city: "Akron",
    state_code: "OH",
    zip: "44311",
    source_url: "https://www.loopnet.com/Listing/1025-S-Broadway-St-Akron-OH/39645924/",
    units: 303,
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "self_storage_flex_building",
      listing_id: "39645924",
      building_sqft: 63675,
      year_built_renovated: "1919/2017",
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page says the building produces income from self-storage units and has 303 self-storage units currently.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage and current unit count.",
    },
  },
  {
    market: "fort-wayne",
    title: "6515 Stellhorn Rd - Next Level Storage",
    address: "6515 Stellhorn Rd",
    city: "Fort Wayne",
    state_code: "IN",
    zip: "46815",
    source_url: "https://www.loopnet.com/Listing/6515-Stellhorn-Rd-Fort-Wayne-IN/39172064/",
    units: 49,
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "storage_condo_units",
      listing_id: "39172064",
      building_sqft: 45400,
      lot_acres: 2.58,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Next Level Storage with 49 RV/Toy Shed/warehouse storage units available for lease or purchase and Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit storage units and Property Subtype = Self-Storage.",
    },
  },
  {
    market: "peoria",
    title: "3101-3211 W Harmon Hwy - approved self-storage conversion",
    address: "3101-3211 W Harmon Hwy",
    city: "Peoria",
    state_code: "IL",
    zip: "61604",
    source_url: "https://www.loopnet.com/Listing/3101-3211-W-Harmon-Hwy-Peoria-IL/38502320/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "self_storage_conversion_opportunity",
      listing_id: "38502320",
      activated_on: "2025-11-19",
      approved_units: 700,
      building_sqft: 84346,
      lot_acres: 12.86,
      source_summary: "LoopNet detail page says the property has special-use permit approval for approximately 700 climate-controlled and drive-up self-storage units and is currently available.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with approved self-storage conversion and Date on Market.",
    },
  },
  {
    market: "san-antonio",
    title: "4930 Callaghan Rd - Secure Spaces Self Storage",
    address: "4930 Callaghan Rd",
    city: "San Antonio",
    state_code: "TX",
    zip: "78228",
    source_url: "https://www.loopnet.com/Listing/4930-Callaghan-Rd-San-Antonio-TX/40133195/",
    list_price: 910000,
    units: 93,
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "operating_self_storage",
      listing_id: "40133195",
      building_sqft: 22500,
      nrsf: 22450,
      noi: 80231,
      cap_rate: "8.82%",
      source_summary: "LoopNet detail page says Secure Spaces Self Storage is a 93-unit, 22,450 NRSF self-storage investment opportunity.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit operating self-storage details.",
    },
  },
  {
    market: "san-antonio",
    title: "Storage 4U Self Storage 2 Portfolio",
    address: "San Antonio portfolio",
    city: "San Antonio",
    state_code: "TX",
    zip: null,
    source_url: "https://www.loopnet.com/Listing/San-Antonio-TX/39167455/",
    units: 808,
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "self_storage_portfolio",
      listing_id: "39167455",
      portfolio_name: "Storage 4U Self Storage 2 Portfolio",
      portfolio_properties: 2,
      nrsf: 95540,
      parking_units: 344,
      parking_nrsf: 115974,
      broker: "CBRE Self Storage Advisory Group",
      source_summary: "LoopNet detail page says CBRE is exclusive listing advisor for a pair of San Antonio self-storage properties with 808 storage units and 344 uncovered parking spaces.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit self-storage portfolio details.",
    },
  },
  {
    market: "san-antonio",
    title: "3608 S Gevers Street Portfolio - Doc's Space Center Self Storage",
    address: "3608 S Gevers St",
    city: "San Antonio",
    state_code: "TX",
    zip: "78210",
    source_url: "https://www.loopnet.com/Listing/3608-S-Gevers-Street-Portfolio/37693214/",
    list_price: 4579000,
    status: "active",
    confidence: "medium",
    raw: {
      evidence_type: "mixed_portfolio_with_self_storage",
      listing_id: "37693214",
      building_sqft: 19800,
      portfolio_properties: 2,
      source_summary: "LoopNet detail page says the portfolio includes Doc's Spacecenter Self Storage and a veterinary practice/hospital property.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit self-storage property in mixed portfolio.",
    },
  },
  {
    market: "columbus",
    title: "750 E 11th Ave - former Gateway Self Storage listing",
    address: "750 E 11th Ave",
    city: "Columbus",
    state_code: "OH",
    zip: "43211",
    source_url: "https://www.loopnet.com/Listing/750-E-11th-Ave-Columbus-OH/8710467/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "former_self_storage_listing",
      listing_id: "8710467",
      source_summary: "LoopNet detail page identifies Gateway Self Storage but says the property is no longer advertised on LoopNet.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "detroit",
    title: "14225 Schaefer Hwy - former self-storage / industrial listing",
    address: "14225 Schaefer Hwy",
    city: "Detroit",
    state_code: "MI",
    zip: "48227",
    source_url: "https://www.loopnet.com/Listing/14225-Schaefer-Hwy-Detroit-MI/38285959/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "former_self_storage_listing",
      listing_id: "38285959",
      activated_on: "2025-10-31",
      building_sqft: 43688,
      lot_acres: 1.78,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Property Subtype = Self-Storage but says it is no longer advertised.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "memphis",
    title: "1699 Airways Blvd - former Airways Storage listing",
    address: "1699 Airways Blvd",
    city: "Memphis",
    state_code: "TN",
    zip: "38114",
    source_url: "https://www.loopnet.com/Listing/1699-Airways-Blvd-Memphis-TN/36739338/",
    units: 1185,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "former_operating_self_storage_listing",
      listing_id: "36739338",
      activated_on: "2025-07-15",
      building_sqft: 146580,
      lot_acres: 6,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Airways Storage with 1,185 climate-controlled units and 80 parking spaces, but says it is no longer advertised.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "san-antonio",
    title: "1301 E Commerce St - former Downtown SA Self Storage listing",
    address: "1301 E Commerce St",
    city: "San Antonio",
    state_code: "TX",
    zip: "78205",
    source_url: "https://www.loopnet.com/Listing/1301-E-Commerce-St-San-Antonio-TX/12355665/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "former_self_storage_listing",
      listing_id: "12355665",
      building_sqft: 80400,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Downtown SA Self Storage but says it is no longer advertised.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "south-bend",
    title: "52447 Portage Rd - former self-storage listing",
    address: "52447 Portage Rd",
    city: "South Bend",
    state_code: "IN",
    zip: "46628",
    source_url: "https://www.loopnet.com/Listing/52447-Portage-Rd-South-Bend-IN/30624303/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "former_self_storage_listing",
      listing_id: "30624303",
      activated_on: "2024-01-10",
      building_sqft: 125000,
      lot_acres: 7.83,
      property_subtype: "Self-Storage",
      parcel_numbers: [
        "71-03-22-153-008.000-009",
        "71-03-22-153-010.000-009",
        "71-03-22-153-009.000-009",
      ],
      source_summary: "LoopNet detail page identifies Property Subtype = Self-Storage and says the property is no longer advertised.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "columbus",
    title: "3784-3800 W Broad St - CubeSmart self-storage super center",
    address: "3784-3800 W Broad St",
    city: "Columbus",
    state_code: "OH",
    zip: "43228",
    source_url: "https://www.loopnet.com/Listing/3784-3800-W-Broad-St-Columbus-OH/17871921/",
    units: 595,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "17871921",
      building_sqft: 120870,
      nrsf: 73300,
      lot_acres: 11.59,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Columbus Self-Storage Super Center-CubeSmart with Property Subtype = Self-Storage and 595 units.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "columbus",
    title: "1521 Harrisburg Pike - 78 self-storage units",
    address: "1521 Harrisburg Pike",
    city: "Columbus",
    state_code: "OH",
    zip: "43223",
    source_url: "https://www.loopnet.com/Listing/1521-Harrisburg-Pike-Columbus-OH/14018804/",
    units: 78,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "14018804",
      activated_on: "2018-10-09",
      building_sqft: 11880,
      lot_acres: 1.18,
      property_subtype: "Self-Storage",
      parcel_number: "570-195795",
      source_summary: "LoopNet detail page identifies Property Subtype = Self-Storage and says Columbus self-storage units for sale, 78 storage units on 1.18 acres.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "dallas",
    title: "3020 Duncanville Rd - Insure Self Storage",
    address: "3020 Duncanville Rd",
    city: "Dallas",
    state_code: "TX",
    zip: "75211",
    source_url: "https://www.loopnet.com/Listing/3020-Duncanville-Rd-Dallas-TX/35554099/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "35554099",
      activated_on: "2025-04-18",
      building_sqft: 19649,
      lot_acres: 1.3,
      property_subtype: "Self-Storage",
      parcel_number: "00000785176000000",
      source_summary: "LoopNet detail page identifies Insure Self Storage with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "dallas",
    title: "3520 Forest Ln - Park Forest Self Storage",
    address: "3520 Forest Ln",
    city: "Dallas",
    state_code: "TX",
    zip: "75234",
    source_url: "https://www.loopnet.com/Listing/3520-Forest-Ln-Dallas-TX/25762622/",
    units: 363,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "25762622",
      activated_on: "2022-05-23",
      building_sqft: 59332,
      lot_acres: 1.88,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Park Forest Self Storage with Property Subtype = Self-Storage and 363 climate-controlled units.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "dallas",
    title: "3737 Frankford Rd - Preferred Self Storage",
    address: "3737 Frankford Rd",
    city: "Dallas",
    state_code: "TX",
    zip: "75287",
    source_url: "https://www.loopnet.com/Listing/3737-Frankford-Rd-Dallas-TX/12559943/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "12559943",
      building_sqft: 57825,
      lot_acres: 3.96,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Preferred Self Storage as a self-storage facility with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "dayton",
    title: "4753 Salem Ave - TurnKey Self Storage",
    address: "4753 Salem Ave",
    city: "Dayton",
    state_code: "OH",
    zip: "45416",
    source_url: "https://www.loopnet.com/Listing/4753-Salem-Ave-Dayton-OH/25779686/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "25779686",
      building_sqft: 50804,
      lot_acres: 4.79,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies TurnKey Self Storage with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "dayton",
    title: "2121 Harshman Rd - self-storage specialty property",
    address: "2121 Harshman Rd",
    city: "Dayton",
    state_code: "OH",
    zip: "45424",
    source_url: "https://www.loopnet.com/Listing/2121-Harshman-Rd-Dayton-OH/19354420/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_self_storage_listing",
      listing_id: "19354420",
      building_sqft: 99099,
      lot_acres: 4.45,
      property_subtype: "Self-Storage",
      parcel_number: "I39-00203-0002",
      source_summary: "LoopNet detail page identifies the property with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "toledo",
    title: "3015 Glendale Ave - self-storage specialty property",
    address: "3015 Glendale Ave",
    city: "Toledo",
    state_code: "OH",
    zip: "43614",
    source_url: "https://www.loopnet.com/Listing/3015-Glendale-Ave-Toledo-OH/32421423/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_self_storage_listing",
      listing_id: "32421423",
      building_sqft: 154875,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies the Toledo property with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "toledo",
    title: "3248 Percentum Rd - self-storage specialty property",
    address: "3248 Percentum Rd",
    city: "Toledo",
    state_code: "OH",
    zip: "43617",
    source_url: "https://www.loopnet.com/Listing/3248-Percentum-Rd-Toledo-OH/6478756/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_self_storage_listing",
      listing_id: "6478756",
      activated_on: "2017-03-27",
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies the Toledo property with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "toledo",
    title: "155 S Superior St - self-storage specialty property",
    address: "155 S Superior St",
    city: "Toledo",
    state_code: "OH",
    zip: "43604",
    source_url: "https://www.loopnet.com/Listing/155-S-Superior-St-Toledo-OH/34875408/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_self_storage_listing",
      listing_id: "34875408",
      activated_on: "2025-02-19",
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies the Toledo property with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "cleveland",
    title: "4553 Johnston Pkwy - Trojan Storage of Cleveland",
    address: "4553 Johnston Pkwy",
    city: "Cleveland",
    state_code: "OH",
    zip: "44128",
    source_url: "https://www.loopnet.com/Listing/4553-Johnston-Pky-Cleveland-OH/9927102/",
    units: 533,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "9927102",
      building_sqft: 63186,
      lot_acres: 5.73,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Trojan Storage of Cleveland with Property Subtype = Self-Storage and 533 self-storage units.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "cleveland",
    title: "2037 Lee Rd - Heights Mini Storage",
    address: "2037 Lee Rd",
    city: "Cleveland Heights",
    state_code: "OH",
    zip: "44118",
    source_url: "https://www.loopnet.com/Listing/2037-Lee-Rd-Cleveland-Heights-OH/11216222/",
    units: 135,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "11216222",
      activated_on: "2018-01-11",
      building_sqft: 8063,
      lot_acres: 0.2,
      property_subtype: "Self-Storage",
      parcel_number: "687-02-034",
      source_summary: "LoopNet detail page identifies Heights Mini Storage with Property Subtype = Self-Storage and 135 units.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "akron",
    title: "750 Liberty Green Dr - Liberty Green Storage XXLarge",
    address: "750 Liberty Green Dr",
    city: "Akron",
    state_code: "OH",
    zip: "44312",
    source_url: "https://www.loopnet.com/Listing/750-Liberty-Green-Dr-Akron-OH/26287679/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "active_self_storage_lease_listing",
      listing_id: "26287679",
      activated_on: "2025-05-15",
      building_sqft: 20957,
      available_sqft: 17250,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page says the property is currently available for lease and identifies Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage.",
    },
  },
  {
    market: "akron",
    title: "711 Johnston St - permitted self-storage use",
    address: "711 Johnston St",
    city: "Akron",
    state_code: "OH",
    zip: "44306",
    source_url: "https://www.loopnet.com/Listing/711-Johnston-St-Akron-OH/13305467/",
    list_price: 1250000,
    status: "active",
    confidence: "medium",
    raw: {
      evidence_type: "active_self_storage_conversion_opportunity",
      listing_id: "36882320",
      building_sqft: 98246,
      lot_acres: 1.62,
      source_summary: "LoopNet detail page says permitted use is self-storage and the property is currently available.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit permitted self-storage use; classified as conversion opportunity.",
    },
  },
  {
    market: "fort-wayne",
    title: "6565 Stellhorn Rd - Next Level Storage lease listing",
    address: "6565 Stellhorn Rd",
    city: "Fort Wayne",
    state_code: "IN",
    zip: "46815",
    source_url: "https://www.loopnet.com/Listing/6565-Stellhorn-Rd-Fort-Wayne-IN/39173072/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "active_self_storage_lease_listing",
      listing_id: "39173072",
      activated_on: "2026-01-22",
      building_sqft: 45400,
      available_sqft: 3900,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Next Level Storage with Property Subtype = Self-Storage and available office/storage space.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage.",
    },
  },
  {
    market: "fort-wayne",
    title: "1405 Rock Dove Rd - self-storage specialty property",
    address: "1405 Rock Dove Rd",
    city: "Fort Wayne",
    state_code: "IN",
    zip: "46814",
    source_url: "https://www.loopnet.com/Listing/1405-Rock-Dove-Rd-Fort-Wayne-IN/18138361/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_self_storage_listing",
      listing_id: "18138361",
      activated_on: "2020-01-09",
      building_sqft: 86090,
      lot_acres: 7.63,
      property_subtype: "Self-Storage",
      parcel_number: "02-11-08-100-006.002-038",
      source_summary: "LoopNet detail page identifies Property Subtype = Self-Storage and describes 86,090 square feet of storage built in 2015.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "fort-wayne",
    title: "630 Sumpter St - Toy Shed Storage Condominiums",
    address: "630 Sumpter St",
    city: "Fort Wayne",
    state_code: "IN",
    zip: "46804",
    source_url: "https://www.loopnet.com/Listing/630-Sumpter-St-Fort-Wayne-IN/8131878/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_storage_condo_listing",
      listing_id: "8131878",
      activated_on: "2017-07-14",
      building_sqft: 22138,
      lot_acres: 0.21,
      property_subtype: "Self-Storage",
      parcel_number: "02-12-06-100-004.001-068",
      source_summary: "LoopNet detail page identifies Toy Shed Storage Condominiums with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "peoria",
    title: "421 E Moneta Ave - self-storage lease listing",
    address: "421 E Moneta Ave",
    city: "Peoria Heights",
    state_code: "IL",
    zip: "61616",
    source_url: "https://www.loopnet.com/Listing/421-E-Moneta-Ave-Peoria-Heights-IL/38951521/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "active_self_storage_lease_listing",
      listing_id: "38951521",
      activated_on: "2026-01-05",
      building_sqft: 7510,
      available_sqft: 7510,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Property Subtype = Self-Storage and current space availability.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage.",
    },
  },
  {
    market: "peoria",
    title: "4400 N Brandywine Dr - U-Haul Moving & Storage",
    address: "4400 N Brandywine Dr",
    city: "Peoria",
    state_code: "IL",
    zip: "61614",
    source_url: "https://www.loopnet.com/Listing/4400-N-Brandywine-Dr-Peoria-IL/10827108/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "10827108",
      activated_on: "2017-12-01",
      building_sqft: 261000,
      lot_acres: 7.25,
      property_subtype: "Self-Storage",
      parcel_numbers: ["14-19-477-007", "14-19-477-001"],
      source_summary: "LoopNet detail page identifies U-Haul Moving & Storage at War Memorial Dr with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "san-antonio",
    title: "2641 Talley Rd - ready-to-develop self-storage site",
    address: "2641 Talley Rd",
    city: "San Antonio",
    state_code: "TX",
    zip: "78253",
    source_url: "https://www.loopnet.com/Listing/2641-Talley-Rd-San-Antonio-TX/35888493/",
    status: "active",
    confidence: "medium",
    raw: {
      evidence_type: "active_self_storage_development_land",
      listing_id: "35888493",
      activated_on: "2025-05-16",
      lot_acres: 1.49,
      parcel_number: "04389-000-0063",
      source_summary: "LoopNet detail page says the land property is currently available and identifies Proposed Use = Self Storage.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with explicit self-storage proposed use; classified as development land.",
    },
  },
  {
    market: "san-antonio",
    title: "8034 Culebra Rd - Extra Space Storage lease listing",
    address: "8034 Culebra Rd",
    city: "San Antonio",
    state_code: "TX",
    zip: "78251",
    source_url: "https://www.loopnet.com/Listing/8034-Culebra-Rd-San-Antonio-TX/34414814/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "active_self_storage_lease_listing",
      listing_id: "34414814",
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies Extra Space Storage with Property Subtype = Self-Storage and available space.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage.",
    },
  },
  {
    market: "san-antonio",
    title: "13600 N IH 35 - Lock & Go Self Storage",
    address: "13600 N IH 35",
    city: "San Antonio",
    state_code: "TX",
    zip: "78233",
    source_url: "https://www.loopnet.com/Listing/13600-N-IH-35-San-Antonio-TX/34494842/",
    units: 150,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "34494842",
      activated_on: "2025-01-15",
      building_sqft: 18640,
      lot_acres: 2.1,
      property_subtype: "Self-Storage",
      parcel_number: "05048-000-0355",
      source_summary: "LoopNet detail page identifies Lock & Go Self Storage with Property Subtype = Self-Storage and 150 units.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "san-antonio",
    title: "10930 Braun Rd - StorageMart / Move It Self Storage Braun",
    address: "10930 Braun Rd",
    city: "San Antonio",
    state_code: "TX",
    zip: "78254",
    source_url: "https://www.loopnet.com/Listing/10930-Braun-Rd-San-Antonio-TX/12753097/",
    units: 521,
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "12753097",
      building_sqft: 73116,
      nrsf: 72063,
      lot_acres: 4.09,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page identifies StorageMart / Move It Self Storage Braun with Property Subtype = Self-Storage and 521 units.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "birmingham",
    title: "185 W Oxmoor Rd - self-storage specialty property",
    address: "185 W Oxmoor Rd",
    city: "Birmingham",
    state_code: "AL",
    zip: "35209",
    source_url: "https://www.loopnet.com/Listing/185-W-Oxmoor-Rd-Birmingham-AL/5096900/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_self_storage_listing",
      listing_id: "5096900",
      activated_on: "2016-12-06",
      building_sqft: 17600,
      lot_acres: 6.91,
      property_subtype: "Self-Storage",
      parcel_numbers: ["29-00-27-2-000-015.001", "29-00-27-2-000-015.000"],
      source_summary: "LoopNet detail page identifies the Birmingham property with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "birmingham",
    title: "2251 Highway 150 - former self-storage proposed-use land",
    address: "2251 Highway 150",
    city: "Birmingham",
    state_code: "AL",
    zip: "35244",
    source_url: "https://www.loopnet.com/Listing/2251-Highway-150-Birmingham-AL/3907754/",
    status: "off_market",
    confidence: "medium",
    raw: {
      evidence_type: "former_self_storage_development_land",
      listing_id: "3907754",
      activated_on: "2016-09-24",
      lot_acres: 23,
      parcel_numbers: ["39-00-29-3-000-009.000", "39-00-29-3-000-011.002"],
      source_summary: "LoopNet detail page says Proposed Use includes Self Storage and says the property is no longer advertised.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "birmingham",
    title: "5952 Service Rd - former self-storage proposed-use land",
    address: "5952 Service Rd",
    city: "Birmingham",
    state_code: "AL",
    zip: "35235",
    source_url: "https://www.loopnet.com/Listing/5952-Service-Rd-Birmingham-AL/15640811/",
    status: "off_market",
    confidence: "medium",
    raw: {
      evidence_type: "former_self_storage_development_land",
      listing_id: "15640811",
      activated_on: "2019-04-05",
      lot_acres: 9.69,
      parcel_number: "12-00-15-4-000-011.001",
      source_summary: "LoopNet detail page says Proposed Use includes Self Storage and says the property is no longer advertised.",
      verification: "public_detail_page",
      rejected_as_active_reason: "No longer advertised on LoopNet.",
    },
  },
  {
    market: "memphis",
    title: "4614 Millbranch Rd - Extra Space Storage managed",
    address: "4614 Millbranch Rd",
    city: "Memphis",
    state_code: "TN",
    zip: "38116",
    source_url: "https://www.loopnet.com/Listing/4614-Millbranch-Rd-Memphis-TN/31380866/",
    status: "off_market",
    confidence: "high",
    raw: {
      evidence_type: "historical_operating_self_storage_listing",
      listing_id: "31380866",
      activated_on: "2024-04-01",
      building_sqft: 73510,
      lot_acres: 6.3,
      property_subtype: "Self-Storage",
      parcel_number: "07-9041-A0-0028",
      source_summary: "LoopNet detail page identifies Extra Space Storage managed property with Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
  {
    market: "west-chester",
    title: "21 Hagerty Blvd - new-construction self-storage units",
    address: "21 Hagerty Blvd",
    city: "West Chester",
    state_code: "PA",
    zip: "19382",
    source_url: "https://www.loopnet.com/Listing/21-Hagerty-Blvd-West-Chester-PA/40266611/",
    status: "active",
    confidence: "high",
    raw: {
      evidence_type: "active_self_storage_lease_listing",
      listing_id: "40266611",
      activated_on: "2026-04-23",
      building_sqft: 128000,
      available_sqft: 16800,
      property_subtype: "Self-Storage",
      source_summary: "LoopNet detail page says the property is currently available for lease and identifies Property Subtype = Self-Storage.",
      verification: "public_detail_page",
      accepted_reason: "Active public detail page with Property Subtype = Self-Storage.",
    },
  },
  {
    market: "west-chester",
    title: "Route 113 Exton - former self-storage proposed development",
    address: "Route 113",
    city: "Exton",
    state_code: "PA",
    zip: "19341",
    source_url: "https://www.loopnet.com/Listing/Route-113-Exton-PA/7012479/",
    status: "off_market",
    confidence: "medium",
    raw: {
      evidence_type: "former_self_storage_development_land",
      listing_id: "7012479",
      activated_on: "2017-05-01",
      lot_acres: 20,
      parcel_number: "33-004-0097.0000",
      source_summary: "LoopNet detail page says proposed development into approximately 135,000 square feet of public storage space.",
      verification: "public_detail_page",
      rejected_as_active_reason: "Historical public detail evidence; no current active availability was verified in this pass.",
    },
  },
];

await db
  .from("external_market_listings")
  .delete()
  .eq("asset_class", "self_storage")
  .eq("source", "free_web_loopnet_detail");

let upserted = 0;
for (const row of rows) {
  const { error } = await db.from("external_market_listings").insert({
    market: row.market,
    asset_class: "self_storage",
    source: "free_web_loopnet_detail",
    source_url: row.source_url,
    title: row.title,
    address: row.address,
    city: row.city,
    state_code: row.state_code,
    zip: row.zip,
    units: row.units ?? null,
    list_price: row.list_price ?? null,
    price_per_unit: null,
    cap_rate: null,
    noi: typeof row.raw.noi === "number" ? row.raw.noi : null,
    status: row.status,
    confidence: row.confidence,
    observed_at: observedAt,
    first_seen_at: observedAt,
    last_seen_at: observedAt,
    raw: row.raw,
  });
  if (error) throw error;
  upserted++;
}

const activeByMarket = rows
  .filter((row) => row.status === "active")
  .reduce<Record<string, number>>((acc, row) => {
    acc[row.market] = (acc[row.market] ?? 0) + 1;
    return acc;
  }, {});

const offMarketByMarket = rows
  .filter((row) => row.status === "off_market")
  .reduce<Record<string, number>>((acc, row) => {
    acc[row.market] = (acc[row.market] ?? 0) + 1;
    return acc;
  }, {});

console.log(JSON.stringify({
  upserted,
  active_rows: rows.filter((row) => row.status === "active").length,
  off_market_rows: rows.filter((row) => row.status === "off_market").length,
  activeByMarket,
  offMarketByMarket,
  source: "free_web_loopnet_detail",
}, null, 2));
